[project]
name = "vocalocator-ssl"
version = "1.1.0"
authors = [
    { name="NeuroStats Lab" },
]
description = "Tool for weakly-supervised sound-source localization of vocal calls"
readme = "README.md"
requires-python = ">=3.11"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
license = "MIT"
dependencies = [
    "h5py>=3.16.0",
    "lightning>=2.6.5",
    "numpy>=2.4.6",
    "pyjson5>=2.0.1",
    "scipy>=1.17.1",
    "torch>=2.13.0",
    "torchaudio>=2.11.0",
]

[project.urls]
Homepage = "https://github.com/neurostatslab/vocalocator"
Issues = "https://github.com/neurostatslab/vocalocator/issues"
